# Generated by Django 4.2 on 2023-08-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activite',
            fields=[
                ('activite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activités/')),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_minimum', models.IntegerField()),
                ('capacite_max', models.IntegerField()),
                ('choix_activite', models.CharField(choices=[('trampoline', 'Trampolines'), ('toboggan', 'Toboggan'), ('mini_golf', 'Mini-Golf'), ('mini_karting', 'Mini-Karting'), ('zone_vr', 'Zone VR'), ('zone_jeux_de_société', 'Zone Jeux de Société')], max_length=50)),
            ],
        ),
    ]
