# Generated by Django 4.2 on 2023-08-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0003_statistique_rapport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='choix_activite',
        ),
    ]
