# Generated by Django 4.2 on 2023-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0005_remove_employe_conges_remove_employe_horaires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('equipement_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_achat', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
