# Generated by Django 4.2 on 2023-09-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0007_alter_rapport_id_alter_statistique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('carte', 'Carte'), ('especes', 'Espèces'), ('autres', 'Autres')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppm.activite')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
    ]
